import { getSupabaseClient, waitForSupabase } from './supabase-client.js';
import { getCurrentUser } from './auth.js';

let sb=null,user=null,quest=null,attempt=null,nodes=[],currentIndex=0,isFirstTime=true,timer=null,startedAt=null,elapsedBefore=0;
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const fmt=s=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;
const qid=()=>Number(new URLSearchParams(location.search).get('id'));

async function init(){
  await waitForSupabase(); sb=getSupabaseClient();
  if(!sb){return fail('Supabase не подключён.');}
  user=await getCurrentUser();
  if(!user){return fail('Для прохождения расследования необходимо войти в аккаунт.');}
  const id=qid(); if(!id)return fail('Не указан ID расследования.');
  const {data:q,error}=await sb.from('quests').select('*').eq('id',id).single();
  if(error||!q)return fail('Расследование не найдено.');
  quest=q;
  const {data:n,error:ne}=await sb.from('clues').select('*').eq('quest_id',id).order('order_index');
  if(ne)return fail('Не удалось загрузить NODE: '+ne.message);
  nodes=n||[];
  const {data:done}=await sb.from('quest_attempts').select('id,status,current_clue_index,started_at,play_time_seconds').eq('user_id',user.id).eq('quest_id',id).eq('status','completed').limit(1);
  isFirstTime=!done?.length;
  await restoreAttempt();
  render(); startTimer();
}
async function restoreAttempt(){
  const {data:existing,error}=await sb.from('quest_attempts').select('*').eq('user_id',user.id).eq('quest_id',quest.id).eq('status','in_progress').order('started_at',{ascending:false}).limit(1).maybeSingle();
  if(error)throw error;
  if(existing){attempt=existing;currentIndex=existing.current_clue_index||0;startedAt=existing.started_at;elapsedBefore=existing.play_time_seconds||0;return;}
  const {data:a,error:e}=await sb.from('quest_attempts').insert({user_id:user.id,quest_id:quest.id,status:'in_progress',started_at:new Date().toISOString(),current_clue_index:0,play_time_seconds:0}).select().single();
  if(e)throw e;attempt=a;startedAt=a.started_at;currentIndex=0;
}
function fail(msg){document.getElementById('invApp').innerHTML=`<div class="inv-card"><div class="inv-kicker">SYSTEM ERROR</div><h2>Не удалось открыть дело</h2><p class="inv-muted">${esc(msg)}</p><a class="inv-btn" href="catalog.html">← Вернуться в каталог</a></div>`}
function elapsed(){return elapsedBefore+(startedAt?Math.max(0,Math.floor((Date.now()-new Date(startedAt).getTime())/1000)):0)}
function startTimer(){clearInterval(timer);timer=setInterval(()=>{const e=document.getElementById('invTimer');if(e)e.textContent=fmt(elapsed())},1000)}
function render(){const pct=Math.min(100,(currentIndex/nodes.length)*100);document.getElementById('invApp').innerHTML=`<div class="inv-top"><div><div class="inv-kicker">CASE ${String(quest.id).padStart(2,'0')}</div><h2 style="margin:5px 0 0">${esc(quest.title)}</h2></div><div class="inv-timer" id="invTimer">${fmt(elapsed())}</div></div><div class="inv-progress"><i style="width:${pct}%"></i></div><div class="inv-case"><main class="inv-card">${renderNode()}</main><aside>${renderChain()}${renderVault()}</aside></div>`;}
function renderNode(){if(currentIndex>=nodes.length)return renderFinal();const n=nodes[currentIndex];return `<div class="inv-chips"><span class="inv-chip orange">NODE ${currentIndex+1}</span><span class="inv-chip">${esc(n.node_type||n.type||'story')}</span><span class="inv-chip">+${Number(n.xp||20)} XP</span></div><h1 style="font-size:clamp(32px,7vw,50px);margin:15px 0 8px">${esc(n.node_title||n.title||`Улика ${currentIndex+1}`)}</h1><p class="inv-muted">${esc(n.caption||'Материал расследования')}</p><div class="inv-notice orange">${esc(n.node_text||n.question||n.caption||n.value||'Изучите материалы и продолжайте расследование.')}</div>${renderMedia(n)}<div id="invTask" style="margin-top:16px">${renderTask(n)}</div>`}
function renderMedia(n){let h='';let media=[];try{media=Array.isArray(n.media)?n.media:(n.media?JSON.parse(n.media):[])}catch{} if(n.value&&['photo','video','audio'].includes(n.type)&&!media.length)media=[{kind:n.type,url:n.value,title:n.caption||''}];for(const m of media){if(!m?.url)continue;if(m.kind==='image'||m.kind==='photo')h+=`<div class="inv-media"><img src="${esc(m.url)}" alt="Фото-улика"><div class="inv-media-head">PHOTO EVIDENCE · ${esc(m.title||'')}</div></div>`;else if(m.kind==='video')h+=`<div class="inv-media"><video controls playsinline src="${esc(m.url)}"></video><div class="inv-media-head">VIDEO EVIDENCE · ${esc(m.title||'')}</div></div>`;else if(m.kind==='audio')h+=`<div class="inv-media inv-audio"><div class="inv-audio-icon">♪</div><div style="flex:1"><div class="inv-media-head" style="padding:0 0 7px">AUDIO EVIDENCE · ${esc(m.title||'')}</div><audio controls src="${esc(m.url)}"></audio></div></div>`;}if(n.document_text)h+=`<div class="inv-media inv-doc"><div class="inv-doc-icon">DOC</div><div><strong>Документ дела</strong><p class="inv-muted" style="margin:4px 0 0">${esc(n.document_text)}</p></div></div>`;return h?`<div class="inv-media-stack">${h}</div>`:''}
function renderTask(n){const type=n.node_type||n.type||'story';if(type==='code')return `<div class="inv-field"><label>КОД ДОСТУПА</label><input class="inv-input" id="invAnswer" inputmode="numeric" placeholder="Введите код с QR-стикера"><div class="inv-actions" style="margin-top:9px"><button class="inv-btn primary" id="invSubmit">Проверить</button><button class="inv-btn ghost" id="invHint">Подсказка</button></div><div id="invResult"></div></div>`;if(type==='question')return `<div class="inv-field"><label>ВАШ ОТВЕТ</label><input class="inv-input" id="invAnswer" placeholder="Введите ответ"><div class="inv-actions" style="margin-top:9px"><button class="inv-btn primary" id="invSubmit">Проверить</button></div><div id="invResult"></div></div>`;if(type==='choice'){let c=[];try{c=Array.isArray(n.choices)?n.choices:JSON.parse(n.choices||'[]')}catch{}return `<div class="inv-field"><label>ВЫБЕРИТЕ ВЕРСИЮ</label>${c.map((x,i)=>`<button class="inv-btn" style="width:100%;text-align:left;margin:5px 0" data-choice="${i}">${i+1}. ${esc(x)}</button>`).join('')}<div id="invResult"></div></div>`}if(type==='final')return renderFinal();return `<div class="inv-actions"><button class="inv-btn primary" id="invCollect">Забрать улику</button></div>`}
function renderChain(){return `<div class="inv-card"><div class="inv-row"><h2>Цепочка</h2><span class="inv-muted">${currentIndex}/${nodes.length}</span></div>${nodes.map((n,i)=>`<div class="inv-node ${i<currentIndex?'done':''} ${i===currentIndex?'current':''}"><strong>${String(i+1).padStart(2,'0')} · ${esc(n.node_title||n.title||`NODE ${i+1}`)}</strong><div class="inv-muted" style="font-size:12px;margin-top:4px">${i<currentIndex?'Улика получена':i===currentIndex?'Текущий NODE':'Заблокировано'}</div></div>`).join('')}</div>`}
function renderVault(){return `<div class="inv-card" style="margin-top:14px"><div class="inv-row"><h2>Архив улик</h2><span class="inv-chip orange" id="evidenceCount">—</span></div><div id="evidenceList"><div class="inv-empty">Загрузка архива…</div></div></div>`}
async function loadEvidence(){if(!attempt)return;const {data}=await sb.from('clue_progress').select('clue_id,completed_at,xp_earned').eq('attempt_id',attempt.id).order('completed_at');const list=document.getElementById('evidenceList'),count=document.getElementById('evidenceCount');if(!list)return;count.textContent=data?.length||0;if(!data?.length){list.innerHTML='<div class="inv-empty">Здесь будут собираться найденные материалы.</div>';return}list.innerHTML=data.map(p=>{const n=nodes.find(x=>x.id===p.clue_id);return `<div class="inv-evidence"><div class="inv-eicon">+</div><div><strong>${esc(n?.evidence_title||n?.node_title||'Улика')}</strong><small>NODE ${nodes.indexOf(n)+1} · +${p.xp_earned||0} XP</small></div></div>`}).join('')}
async function gainXP(amount){if(!isFirstTime||!user)return;const {data:p,error}=await sb.from('profiles').select('xp,level').eq('id',user.id).single();if(error||!p)return;let xp=(p.xp||0)+amount,level=p.level||1;while(xp>=1000*level){xp-=1000*level;level++}await sb.from('profiles').update({xp,level}).eq('id',user.id)}
async function completeNode(n,extraXp=0){const {data:existing}=await sb.from('clue_progress').select('id').eq('attempt_id',attempt.id).eq('clue_id',n.id).maybeSingle();const xp=Number(n.xp||20)+extraXp;if(!existing)await sb.from('clue_progress').insert({attempt_id:attempt.id,clue_id:n.id,code_solved:true,answer_solved:true,xp_earned:xp,completed_at:new Date().toISOString()});await gainXP(xp);currentIndex++;await sb.from('quest_attempts').update({current_clue_index:currentIndex,play_time_seconds:elapsed()}).eq('id',attempt.id);render();await loadEvidence();if(currentIndex>=nodes.length)await finishQuest()}
async function finishQuest(){clearInterval(timer);await sb.from('quest_attempts').update({status:'completed',completed_at:new Date().toISOString(),play_time_seconds:elapsed(),current_clue_index:nodes.length}).eq('id',attempt.id);if(isFirstTime){await gainXP(20);isFirstTime=false}}
function renderFinal(){return `<div class="inv-center"><div class="inv-kicker">CASE CLOSED</div><h1>Расследование завершено.</h1><p class="inv-muted">${esc(quest.title)}</p><div class="inv-bigcode">${esc(quest.final_coords||'Финальная точка открыта')}</div><div class="inv-notice">Все NODE пройдены. Финальная информация доступна.</div><div class="inv-actions" style="justify-content:center;margin-top:16px"><a class="inv-btn primary" href="catalog.html">К другим делам</a></div></div>`}
function bind(){const n=nodes[currentIndex];if(!n)return;if(document.getElementById('invCollect'))document.getElementById('invCollect').onclick=()=>completeNode(n);if(document.getElementById('invHint'))document.getElementById('invHint').onclick=()=>document.getElementById('invResult').innerHTML='<div class="inv-notice orange inv-alert">Сопоставьте текст, медиа и ранее найденные улики.</div>';document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.choice);let correct=Number(n.correct_choice??0);if(i===correct)completeNode(n);else document.getElementById('invResult').innerHTML='<div class="inv-notice inv-error inv-alert">Эта версия не подтверждается уликами.</div>'});const submit=document.getElementById('invSubmit');if(submit)submit.onclick=async()=>{const value=(document.getElementById('invAnswer')?.value||'').trim().toLowerCase();const type=n.node_type||n.type;const target=String(type==='code'?(n.code||''):(n.answer||'')).trim().toLowerCase();if(value&&value===target)completeNode(n);else document.getElementById('invResult').innerHTML='<div class="inv-notice inv-error inv-alert">Не совпадает. Изучите материалы ещё раз.</div>'}}
const originalRender=render;render=async function(){originalRender();bind();await loadEvidence()};
init().catch(e=>fail(e.message||'Неизвестная ошибка'));
